import React from 'react';
import { LegalLayout, type LegalSection } from '../components/LegalLayout';

const sections: LegalSection[] = [
{
  id: 'interpretation-definitions',
  title: 'Interpretation and Definitions',
  body: [
  <><p>We use Your Personal Data to provide and improve the Service. We collect, use, and disclose Your information as described in this Privacy Policy and, where required by applicable law, only where We have a valid legal basis to do so, including Your consent (where consent is required).</p><h3 className="font-display text-lg font-bold uppercase tracking-[0.08em] text-chalk">Interpretation</h3><p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p></>,
  <><h3 className="font-display text-lg font-bold uppercase tracking-[0.08em] text-chalk">Definitions</h3><p>For the purposes of this Privacy Policy:</p><ul><li><strong>Account</strong> means a unique account created for You to access Our Service or parts of Our Service.</li><li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li><li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to OmneScene AI Inc., 201 Mission Street, Suite 1200, San Francisco, CA 94105, USA.</li><li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website, among its many uses.</li><li><strong>Country/State</strong> refers to: California, United States.</li><li><strong>Device</strong> means any device that can access the Service, such as a computer, a cell phone or a digital tablet.</li><li><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual. We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</li><li><strong>Service</strong> refers to the Website.</li><li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, provide the Service on behalf of the Company, perform services related to the Service or assist the Company in analyzing how the Service is used.</li><li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li><li><strong>User</strong> means any individual who accesses or uses the Service.</li><li><strong>Website</strong> refers to Omnescene, accessible from <a href="https://omnescene.com/" rel="external nofollow noopener" target="_blank" className="text-cyan hover:text-cyan-soft">https://omnescene.com/</a>.</li><li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li></ul></>]

},
{
  id: 'collecting-using-personal-information',
  title: 'Collecting and Using Your Personal Information',
  body: [
  <><h3 className="font-display text-lg font-bold uppercase tracking-[0.08em] text-chalk">Types of Data Collected</h3><h4 className="mt-5 font-display text-base font-bold uppercase tracking-[0.06em] text-chalk">Personal Data</h4><p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p><ul><li>Email address</li><li>First name and last name</li></ul><h4 className="mt-5 font-display text-base font-bold uppercase tracking-[0.06em] text-chalk">Usage Data</h4><p>Usage Data is collected automatically when using the Service.</p><p>Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of Our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p><p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device&apos;s unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p><p>We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p></>,
  <><h4 className="font-display text-base font-bold uppercase tracking-[0.06em] text-chalk">Tracking Technologies and Cookies</h4><p>We use tracking technologies (such as cookies) to track the activity and to improve Our Service. The technologies We use may include:</p><ul><li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of Our Service.</li><li><strong>Web Beacons.</strong> Certain sections of Our Service may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages and for other related website statistics.</li></ul><p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.</p><p>Where required by law, We use non-essential cookies only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.</p><p>We use both Session and Persistent Cookies for the purposes set out below:</p><ul><li><strong>Necessary / Essential Cookies</strong><br />Type: Session Cookies<br />Administered by: Us<br />Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.</li><li><strong>Cookies Policy / Notice Acceptance Cookies</strong><br />Type: Persistent Cookies<br />Administered by: Us<br />Purpose: These Cookies identify whether users have accepted the use of cookies on the Website and record the consent choices You have made.</li><li><strong>Functionality Cookies</strong><br />Type: Persistent Cookies<br />Administered by: Us<br />Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering Your Account login details or language preference.</li></ul></>,
  <><h3 className="font-display text-lg font-bold uppercase tracking-[0.08em] text-chalk">Use of Your Personal Data</h3><p>The Company may use Personal Data for the following purposes:</p><ul><li><strong>To provide and maintain Our Service</strong>, including to monitor the usage of Our Service.</li><li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service and provide access to available functionality.</li><li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for products, items or services You have purchased or any other contract with Us through the Service.</li><li><strong>To contact You:</strong> by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates, informative communications, products or contracted services, including necessary security updates.</li><li><strong>To provide You</strong> with news, special offers, and general information about similar goods, services and events. We send marketing communications only where permitted by applicable law. You may opt out using the unsubscribe link or by contacting Us.</li><li><strong>To manage Your requests:</strong> to attend and manage Your requests to Us.</li><li><strong>For business transfers:</strong> to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li><li><strong>For other purposes</strong>, such as data analysis, identifying usage trends, determining the effectiveness of promotional campaigns, and evaluating and improving Our Service, products, services, marketing and Your experience.</li></ul><p>We may share Your Personal Data with Service Providers, in connection with business transfers, with Affiliates, with other users in public areas of the Service, or with Your consent.</p></>]

},
{
  id: 'text-messages',
  title: 'Text Messages Privacy Notice',
  body: [
  <p>You have the option to receive text (SMS) messages from Us. If You opt in, We will send updates, notifications, and other communications as described below. We will collect and store information provided in connection with text messaging, such as Your phone number, the date and method of consent, and message delivery and read information.</p>,
  <p>No mobile information will be shared with or sold to third parties or affiliates for marketing or promotional purposes. Phone numbers and consent records collected for texting are never shared with anyone for any purpose, except Service Providers that technically have to handle them to deliver the texts.</p>,
  <p>Consent to receive text messages is not a condition of any purchase or use of Our Service. If You consent to receive SMS from Us, You agree to receive messages related to:</p>,
  <ul><li>Customer care and support</li><li>Account notifications, such as activity, status, or renewal reminders</li><li>Delivery notifications and updates</li><li>Authentication messages, such as one-time passwords (OTP) and passcodes</li><li>Security alerts</li><li>Marketing and promotional offers</li></ul>,
  <p>Reply STOP to opt-out. Reply HELP for support. Message &amp; data rates may apply. Messaging frequency may vary. Carriers are not liable for delayed or undelivered messages.</p>]

},
{
  id: 'retention',
  title: 'Retention of Your Personal Data',
  body: [
  <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy, including to comply with legal obligations, resolve disputes, and enforce legal agreements and policies.</p>,
  <p>Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods and We may delete or anonymize data sooner:</p>,
  <ul><li><strong>Account Information:</strong> retained for the duration of Your Account relationship plus up to 24 months after account closure.</li><li><strong>Customer Support Data:</strong> support tickets and correspondence, and chat transcripts, up to 24 months.</li><li><strong>Usage Data:</strong> website analytics data and server logs up to 24 months from collection.</li></ul>,
  <p>We may retain Personal Data longer where necessary for legal obligations, legal claims, Your explicit request, or technical limitations in backup systems. When retention periods expire, We securely delete or anonymize Personal Data. Residual copies may remain in encrypted backups for a limited period.</p>]

},
{
  id: 'transfer',
  title: 'Transfer of Your Personal Data',
  body: [
  <p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in other places where the parties involved in processing are located. This means information may be transferred to and maintained on computers located outside Your jurisdiction where data protection laws may differ.</p>,
  <p>Where required by applicable law, We will ensure international transfers are subject to appropriate safeguards and supplementary measures. No transfer will take place unless adequate controls are in place, including the security of Your data.</p>]

},
{
  id: 'delete',
  title: 'Delete Your Personal Data',
  body: [
  <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>,
  <p>You may update, amend, or delete Your information by signing in to Your Account, if You have one, and visiting account settings. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.</p>,
  <p>We may need to retain certain information when We have a legal obligation or lawful basis to do so.</p>]

},
{
  id: 'disclosure',
  title: 'Disclosure of Your Personal Data',
  body: [
  <h3 className="font-display text-lg font-bold uppercase tracking-[0.08em] text-chalk">Business Transactions</h3>,
  <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before it becomes subject to a different Privacy Policy.</p>,
  <h3 className="font-display text-lg font-bold uppercase tracking-[0.08em] text-chalk">Law Enforcement</h3>,
  <p>Under certain circumstances, the Company may disclose Your Personal Data if required by law or in response to valid requests by public authorities.</p>,
  <h3 className="font-display text-lg font-bold uppercase tracking-[0.08em] text-chalk">Other Legal Requirements</h3>,
  <p>The Company may disclose Your Personal Data in the good-faith belief that such action is necessary to comply with a legal obligation, protect and defend the rights or property of the Company, prevent or investigate wrongdoing, protect personal safety, or protect against legal liability.</p>]

},
{
  id: 'security',
  title: 'Security of Your Personal Data',
  body: [
  <p>The security of Your Personal Data is important to Us, but no method of transmission over the Internet or electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>]

},
{
  id: 'children',
  title: "Children's and Minors' Privacy",
  body: [
  <p>The Service is not directed to, and We do not knowingly collect Personal Information from, anyone under the age of 16.</p>,
  <p>If You are a parent or guardian and believe Your child has provided Us with Personal Information, please contact Us. If We become aware that We have collected it from anyone under 16, We will take steps to remove it as soon as reasonably possible.</p>,
  <p>Some countries and states set a higher age at which an individual can consent to processing. Where We rely on consent and applicable law sets an age higher than 16, We may require parental consent.</p>]

},
{
  id: 'links',
  title: 'Links to Other Websites',
  body: [
  <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>,
  <p>We have no control over and assume no responsibility for the content, privacy policies or practices of third-party sites or services.</p>]

},
{
  id: 'changes',
  title: 'Changes to this Privacy Policy',
  body: [
  <p>We may update Our Privacy Policy from time to time by posting the new Privacy Policy on this page.</p>,
  <p>We will let You know via email and/or a prominent notice on Our Service prior to a change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>,
  <p>You are advised to review this Privacy Policy periodically. Changes are effective when they are posted on this page.</p>]

},
{
  id: 'contact',
  title: 'Contact Us',
  body: [
  <p>If You have any questions about this Privacy Policy, You can contact Us:</p>,
  <ul><li>By email: support@omnescene.com</li><li>By visiting this page on Our Website: <a href="https://omnescene.com/" target="_blank" rel="noopener noreferrer" className="text-cyan hover:text-cyan-soft">omnescene.com</a></li><li>By phone: +94 11 239 6745</li></ul>]

}];


export function Privacy() {
  return (
    <LegalLayout
      eyebrow="Legal"
      title="Privacy Policy"
      updated="August 18, 2026"
      intro="This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You."
      sections={sections} />);


}